# Generated by Django 4.2.1 on 2023-05-27 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id_sujet', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('titre_sujet', models.CharField(max_length=255)),
                ('id_groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupes.groupe')),
            ],
        ),
    ]
