# Generated by Django 4.2.1 on 2023-05-27 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encadrents', '0001_initial'),
        ('dep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id_groupe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_groupe', models.CharField(max_length=100)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encadrents.encadrent')),
                ('id_departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep.departement')),
            ],
        ),
    ]
