# Generated by Django 4.1.7 on 2023-07-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
